### ISSUE TITLE
Problems unmounting chroot after logging out of a desktop session

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1456]
After I log out of my lxde-desktop, gnome-desktop, or other desktops for that matter, I'm getting a message about another instance using the chroot -

`Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.`

and a ps -ef shows me no crouton processes - that I'm familiar with at least.

When I ran unmount-chroot with the '-p' option, it spit this out:

`102 10692 1239 0 16:41 ? 00:00:00 dbus-daemon --system --fork`

I had to force it (-f) to unmount, the 'y' opton didn't do it.

Maybe crouton is being *too* thorough ;)

**Comment by dnschneid** [comment]
Could you grab the latest version of crouton and repro with the updated `unmount-chroot -p`?  It was only printing out one process :(

**Comment by DennisLfromGA** [comment]
Will do - gimme 5.

**Comment by dnschneid** [comment]
It looks like session-manager is inheriting orphan processes, which is screwing up the unmount-chroot logic.

**Comment by DennisLfromGA** [comment]
I just updated the chroot (942fcc6) and, after it finished I first tried to rename/move the chroot and got this:
```
sudo edit-chroot -m trusty 1-trusty
Not unmounting /mnt/stateful_partition/crouton/chroots/1-trusty as another instance is using it.
```

When I ran unmount-chroot, I got this:
```
sudo unmount-chroot 1-trusty
Not unmounting /mnt/stateful_partition/crouton/chroots/1-trusty as another instance is using it.

chronos@localhost ~ $ sudo unmount-chroot -p 1-trusty
18445 dbus-daemon --system --fork
18469 /usr/sbin/console-kit-daemon --no-daemon
18534 /usr/lib/policykit-1/polkitd --no-debug
18555 /lib/systemd/systemd-logind
Not unmounting /mnt/stateful_partition/crouton/chroots/1-trusty as another instance is using it.
```

**Comment by DennisLfromGA** [comment]
Wow! `mount|grep crouton|wc -l` gives me **42**

**Comment by dnschneid** [comment]
OK, should be fixed now.

**Comment by DennisLfromGA** [comment]
Okay, I'll log out and then get back in and do an update - be back soon.
{ I can be a *real* PITA sometimes ;( }

**Comment by dnschneid** [comment]
No way, your bug reports and testing are invaluable.

**Comment by DennisLfromGA** [comment]
[ Note to self: just logging out doesn't get everything unmounted, you *have* to reboot. ]
Updated (cafd389) and got excellent results :+1: 
```
...
Unmounting /mnt/stateful_partition/crouton/chroots/1-trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/1-trusty...
chronos@localhost ~ $ mount|grep crouton
chronos@localhost ~ $ 
```

You're the man! ;)

**Comment by yisheng-on-linux** [comment]
Did a fresh install tonight (3/6 1am ET) and I still get 

*Not unmounting /mnt/stateful_partition/crouton/chroots....as another instance is using it.*

**Comment by DennisLfromGA** [comment]
@yisheng-on-linux,

What shows up when you enter `sudo unmount-chroot -p [chrootname]`?
That should let you know what's still hanging it up.

**Comment by yisheng-on-linux** [comment]
/mnt/stateful_partition/crouton/chroots/trusty not found.
17399 dbus-daemon --system --fork

**Comment by yisheng-on-linux** [comment]
interesting....
on a lark, I decided to kill ol' 17399.
ran again and my cupsd showed up
killed it and ran again
2 other processes came up in the same kill/try again order 
(both were inoticoming which I use to monitor the Downloads dir and move things off so when I am in the chrome side and download I don't forget to move it out as I use guest mode and it gets cleared on reboot)

cupsd is run from rc.local
inoticoming are both run from the xfce startup manager

**Comment by DennisLfromGA** [comment]
The dbus-daemon process I thought was taken care of in the https://github.com/dnschneid/crouton/commit/cafd38913ca29251e98424a998ded8c37f4655a6 update, looks like it's still a problem for you though.

**Comment by dnschneid** [comment]
Could you please post the output of `croutonversion`?

**Comment by Improbus** [comment]
I'm having this issue as well output as follows.

```
waiting for X server to shut down xfce4-volumed: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
(EE) Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

chronos@localhost / $ sudo unmount-chroot -p trusty
 9499 dbus-daemon --system --fork
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

chronos@localhost / $ sudo enter-chroot -n trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)blah@localhost:~$ croutonversion
crouton: version 1-20150119001004~master:91d1d6cc
release: trusty
architecture: amd64
targets: xfce
host: version 6680.64.0 (Official Build) stable-channel swanky 
(trusty)dan@localhost:~$ exit
logout
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
chronos@localhost / $ sudo unmount-chroot -f trusty
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ 
```

Hopefully that output is useful in your debugging.  I have tried updating crouton, chroot, and rebooting the chromebook.  I have also run apt-get update, apt-get upgrade, apt-get autoremove, and apt-get autoclean.  All produced the same result.

**Comment by dnschneid** [comment]
@Improbus your chroot is still old.  Please follow the steps [here](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting) for updating your chroot, and make sure the thing succeeds.

**Comment by Improbus** [comment]
Dave it is now working correctly.  I appreciate your prompt response and instruction.  Have a good one.

```
chronos@localhost / $ sudo enter-chroot -n trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)blah@localhost:~$ exit
logout
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ 
```

**Comment by khizeroddin** [comment]
i m having issue pls help me out 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1514141414.918429 sender=:1.13 -> destination=:1.42 serial=699 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
