### ISSUE TITLE
cannot install kernel driver .ko file

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#3434]
```
name: roo
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/roo...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,lxde
host: version 9592.96.0 (Official Build) stable-channel chell 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Sat Sep 16 09:55:17 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

I followed the instructions at ...wiki/Build-chrome-os-kernel-and-kernel-modules and built the .ko drivers modules for usbip.  I put the ko files in my root folder.  Now when I run `insmod usbip-core.ko` as root I get the error ...

```
insmod: ERROR: could not insert module usbip-core.ko: Operation not permitted
```
I assume I need to disable module locking.  How do I do this?

**Comment by divx118** [comment]
See https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules#enable-loading-of-kernel-modules the script I created is IMO the easiest way.
In a crosh shell:
```
$ cd ~/Downloads
$ wget https://raw.githubusercontent.com/divx118/crouton-packages/master/change-kernel-flags
$ sudo sh ~/Downloads/change-kernel-flags
```

**Comment by mark-hahn** [comment]
thanks

**Comment by mark-hahn** [comment]
The repo says "Virtual box modules and the repo is currently broken" so I
didn't try it before.  Is it fixed now?

**Comment by divx118** [comment]
The kernel headers yes, but the script to enable loading kernel modules
(change-kernel-flags) should still work.

**Comment by mark-hahn** [comment]
Thanks mucho.

You need to make that more clear for those of us who have trouble
understanding this stuff.  It would have saved me a lot of trouble.

**Comment by divx118** [comment]
@mark-hahn Yeah sorry, you are right. I am going to update the README.md so it will be more clear. Note that after or before each chromeos update you will need to rerun the script again. 
The script will detect which kernel will be booted on a reboot. So if an update is pending and you need to reboot for that update then you can also first run that script (it will patch the right kernel) and then reboot to update. This will save you a reboot.

**Comment by mhantsch** [comment]
I'm also trying to install kernel modules (cifs.ko). I think I have followed all the instructions in https://github.com/divx118/cifs/blob/master/README.md but insmod still fails:

...
chronos@localhost / $ sudo crossystem | grep dev_boot
dev_boot_usb           = 1                              # Enable developer mode boot from USB/SD (writable)
dev_boot_legacy        = 1                              # Enable developer mode boot Legacy OSes (writable)
dev_boot_signed_only   = 0                              # Enable developer mode boot only from official kernels (writable)
chronos@localhost / $ sudo insmod /usr/local/modules/x86_64_3.8.11/cifs.ko 
insmod: ERROR: could not insert module /usr/local/modules/x86_64_3.8.11/cifs.ko: Operation not permitted
chronos@localhost / $ dmesg | tail
[...]
[  557.261293] Chromium OS LSM: init_module denied module="/usr/local/modules/x86_64_3.8.11/cifs.ko" pid=7793 cmdline="insmod /usr/local/modules/x86_64_3.8.11/cifs.ko"
...

What else do I need to look into? I ran out of ideas.

This is on ChromeOS 5.0.3325.209.

**Comment by divx118** [comment]
@mhantsch Did you follow
```
$ cd ~/Downloads
$ wget https://raw.githubusercontent.com/divx118/crouton-packages/master/change-kernel-flags
$ sudo sh ~/Downloads/change-kernel-flags
```
I will update these steps to since wget isn't available anymore and you can't execute from ~/Downloads anymore:
```
$ sudo mkdir -p /usr/local/bin/
$ cd /usr/local/bin/
$ sudo curl -O https://raw.githubusercontent.com/divx118/crouton-packages/master/change-kernel-flags
$ sudo chmod a+x change-kernel-flags
$ sudo change-kernel-flags
```

**Comment by mhantsch** [comment]
@divx118 Yes, I did something similar to that effect.

Here's the current state:

```
chronos@localhost ~ $ sudo change-kernel-flags 
/tmp/change-kernel-flags.hKv.4
make_dev_ssd.sh: INFO: Saving Kernel B config to /tmp/change-kernel-flags.hKv.4
make_dev_ssd.sh: INFO: (Kernels have not been resigned.)
"lsm.module_locking=0"  is already added to the kernel cmdline.

"lsm.module_locking=0" are already added to the kernel cmdline.
If you wish to revert the original kernel, run "change-kernel-flags -r"
which will give you the option to copy back the original kernel
from an earlier created backup.

chronos@localhost ~ $ sudo insmod /usr/local/modules/x86_64_3.8.11/cifs.ko 
insmod: ERROR: could not insert module /usr/local/modules/x86_64_3.8.11/cifs.ko: Operation not permitted
chronos@localhost ~ $ sudo insmod /usr/local/modules/x86_64_3.8.11/md4.ko 
insmod: ERROR: could not insert module /usr/local/modules/x86_64_3.8.11/md4.ko: Operation not permitted
chronos@localhost ~ $ dmesg | tail -2
[ 2461.536696] Chromium OS LSM: init_module denied module="/usr/local/modules/x86_64_3.8.11/cifs.ko" pid=18993 cmdline="insmod /usr/local/modules/x86_64_3.8.11/cifs.ko"
[ 2465.800668] Chromium OS LSM: init_module denied module="/usr/local/modules/x86_64_3.8.11/md4.ko" pid=18998 cmdline="insmod /usr/local/modules/x86_64_3.8.11/md4.ko"
```

Also, `sudo change-kernel-flags -i` reports that kernel config includes `lsm_module_locking=0`

```
...
Config:
console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=%U/PARTNROFF=1 hashtree=PARTUUID=%U/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=678aad71bf12657b24e84425bf4a31550d6cd41e salt=498e2df781f0d633b8003d99bb407b534a9c8f1662b7d39c579be5d6e61f1b2a" noinitrd vt.global_cursor_default=0 kern_guid=%U add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3   lsm.module_locking=0
...
```

Any other ideas what I should be checking? This is on an original Google Pixel (2013) with latest chromeos updates.

**Comment by divx118** [comment]
@mhantsch Just to be sure did you reboot after running the script change-kernel-flags?

**Comment by mhantsch** [comment]
@divx118 yup, even multiple times when it did not work right away. Reverted with `change-kernel-flags -r` and rebooted, then went forward again and rebooted. I can't get my head straight what I am missing.

**Comment by divx118** [comment]
@mhantsch Hmm well powerwashing shouldn't be needed and is in 99.99% of the cases not the solution. Just let take some time to troubleshoot this properly instead of an unneeded powerwash.
It is really strange I would get it if the modules don't work, because they are build quite a while back. However, you get:
```
Chromium OS LSM: init_module denied....
```
And you should get
```
Chromium OS LSM: init_module locking-ignored ....
``` 
Which normally suggest that `lsm_module_locking=0` is not set in the kernel config.
I see if I can replicate it on my old chromebook which is running also 3.8.11 (my son is still using it)

**Comment by xinheng0816** [comment]
Hello all
Sorry for interupt!   
Someone can guide me how to install compile and install usbip driver in RedHat system ?
BTW, I downlod all source code with verison = Linux version 3.10.0-514.el7.x86_64.   When I tied to build usbip module,  it seems always nothing happen and the expected kos (usbip-core.ko & usbip-host.ko) can't be generated.   
Thank you all!
