### ISSUE TITLE
Display colors in Chrome are corrupted after switching from chroot.

### ISSUE THREAD

**Issue by corlesss** [dnschneid/crouton#3791]
```
chronos@localhost / $ sudo edit-chroot -all
name: artful
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/artful...
crouton: version 1-20180611074759~master:3697b784
release: artful
architecture: amd64
xmethod: xorg
targets: xorg,extension,keyboard,cli-extra
host: version 10718.22.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-17845-gab54fe74d4f3 #1 SMP PREEMPT Wed Jun 13 22:23:21 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/artful...
```

#### Please describe your issue:
Recently whenever I switch between Chrome and Ubuntu the colors on the Chrome session become corrupted. If I return to Ubuntu, the colors are back to normal; but if I go back to Chrome then they're messed up again. Even if I end the Ubuntu session the colors are still corrupted in Chrome. The only thing that fixes the display is turning off the machine and turning it back on. But the issue comes back when I start the chroot and switch back to Chrome.

I attempted to take a screen shot of the corrupted screen; but when I viewed it after rebooting it showed the colors as if the screen was not messed up.

So I took a picture of the screen;
![20180620_001135](https://user-images.githubusercontent.com/40257903/41640749-07644292-7420-11e8-8cb6-5cf435ed388f.jpg)
and a screenshot of the exact same screen moments later
![screenshot 2018-06-20 at 12 11 48 am](https://user-images.githubusercontent.com/40257903/41640753-0bd12bb0-7420-11e8-8270-71967af5cae3.png)

I am on an Asus c302ca on the Beta Channel (v. 68.0.3440.25). I updated the chroot, and there were no issues that came up; but the problem still persisted. This issue only came up within the last day; and the only change is that an update for ChromeOS was installed today as well.

**Comment by corlesss** [comment]
I did attempt to use <kbd>search</kbd>+<kbd>ctrl</kbd>+<kbd>h</kbd>; after making sure that I didn't set high-contrast mode before starting the chroot in xorg. But after I returned back to the corrupted Chrome desktop, the effect didn't reverse the corrupted coloring. Instead it just seemed to make the effect stronger rather than reverse it. Almost as if the corruption seems to be affecting the screen after high-contrast mode is applied.

Other things that I note is that the distortion seems to effect the edges of images and text most; creating an 'outline-like' effect on some things. Whereas with high-contrast mode it seems to mostly invert colors directly. I was also playing with display settings and some features of the menus seem to revert to normal when they're 'unfocused' but return back to distorted when they regain focus. 

I did do some research for other people with the same issues; and aside from #3805 the only other reference to this issue is a [post on Reddit](https://www.reddit.com/r/Crouton/comments/8subfe/another_update_another_proble/) of another use with a c302.

**Comment by DennisLfromGA** [comment]
@corlesss,

Thanx for troubleshooting this issue and providing a workaround.

I saw @wollanup's earlier reference to nightlight mode and that seemed a likely candidate but didn't follow-up, glad you did.

I'm not sure if this is a crosbug, an upstream bug, or what so we'll let the devs decide - if they get a chance to look at it.

-**DennisLfromGA**

**Comment by pshotton** [comment]
I have exactly the same issue. Switching back from ubuntu to chrome os results in the screen colours being corrupted. Toggling the night light restores the screen to normal.
I'm running chrome os Version 69.0.3473.0 (Official Build) dev (64-bit) - I think this issue started happening on the last update. Also since this update my second monitor has been displaying over-bright and washed out looking in chrome os (it's fine in ubuntu). I wonder if there's a connection?

**Comment by Driveling-Discourse** [comment]
Seeing the same issue on my pixelbook after updating to 69.0.3473.0 switching from Ubuntu chroot to ChromeOS. Will give disabling nightlight a try but also found that a quick switch to dev console (ctrl+alt+reload -> ctrl+alt+back) then back to chromeOS clears it up as well (until you switch again to / from the chroot again).

**Comment by campbebj** [comment]
Same issue here. toggling nightlight will reset the colors to normal.

**Comment by pshotton** [comment]
Yes, I've been experiencing that bug too, I think they are related. The most recent Dev channel upgrade fixed the 2nd monitor washout problem, but stopped the night light toggle from restoring normal colour after a switch back from crouton. Today I updated my chroot and now I'm back to having the colour issue fixed by toggling night light.

**Comment by bdp973** [comment]
This started for me after updating Chrome OS to 68.0.3440.87 today.  I have an Asus C302C.  It looks as if the color palette changes to 8-bit or less when I switch back from chroot (which is a Ubuntu Unity desktop install).  However, toggling the Night Light and switching to and from dev console did not fix the issue in my case.

**Comment by mezl** [comment]
I have the same problem on my Pixelbook as well. I am using Chrome OS 70.0.3524.2 dev channel and Ubuntu 16.04.
I found a quick way to work around to fix this problem is to rotate the screen 360 degrees by press  `ctrl+shift+refresh(F2)` button 3 times. This will temporarily fix this problem.

**Comment by corlesss** [comment]
Just an update,

I recently updated my C302 and found that the bug has finally disappeared for me. I didn't bother to check for an update or two so I can't say which one fixed it.

Right now I'm on Beta build 69.0.3497.58.

Since people have said that it was affecting them I'm not going to close this issue; but if somebody else thinks it should be closed I'll leave it up to them.

**Comment by Cerebus** [comment]
Same problem on caroline, but none of these workarounds fix the issue; I have to reboot.

Version 68.0.3440.118 (Official Build) (64-bit)
10718.88.2 (Official Build) stable-channel caroline
Google_Caroline.7820.356.0

**Comment by StephanX** [comment]
Affecting me as well.  The toggle nightlight, rotate screen, and switch to dev console tricks all work for me (I find simply flipping to tablet mode the quickest solution.) 

Google Chrome | 69.0.3497.95 (Official Build) beta (64-bit)
Platform | 10895.56.0 (Official Build) beta-channel eve
Firmware Version | Google_Eve.9584.160.0

**Comment by cessien** [comment]
I'm seeing this as well, I think it's related to the mesa driver on chrome os. Here is what spits out of the `chrome://gpu` logs after changing tty sessions

```
[14066:14072:0920/064101.637986:WARNING:screen_manager.cc(114)] : Display controller (crtc=35) already present.
[14066:14072:0920/064101.638306:VERBOSE1:drm_display.cc(104)] : DRM configuring: device=/sys/devices/pci0000:00/0000:00:02.0/drm/card0 crtc=35 connector=57 origin=0,0 size=0x0
[14066:14072:0920/064102.377278:ERROR:drm_display.cc(177)] : Failed to set color matrix for display: crtc_id = 35
[14066:14072:0920/064102.377356:ERROR:drm_display.cc(186)] : Failed to set gamma tables for display: crtc_id = 35
[14066:14072:0920/064148.315988:WARNING:screen_manager.cc(114)] : Display controller (crtc=35) already present.```

(1) Tried running `chrome://gpuclean` to no avail
(2) Another workaround is to switch resolutions and then to switch back

**Comment by ascension2020** [comment]
My Pixelbook updated to 69.0.3497.95 today and I am seeing the same issue. Swapping out of the chroot distorts the colors in the ChromeOS. It looks like they are 8 bit. Toggling the nightlight setting restores the colors, but it has to be done each time I switch in and out of the chroot.

Rebooting also fixes the colors.

I have not tried the other workarounds in this bug report since toggling the nightlight works.

The chroot is using xenial with the Gnome desktop environment.

![image](https://user-images.githubusercontent.com/14060340/45869781-8dd97800-bd46-11e8-8f46-59bc133309f8.png)

**Comment by gecynd** [comment]
I also have this issue, unfortunately.

**Comment by thrift24** [comment]
Same issue, switching to dev console seems to be the easiest way to remove it, but kind of a pain.

**Comment by mikehgentry** [comment]
This seems to be fixed for me using Buster chroots / Chrome OS Version 70.0.3538.76 (Official Build) (64-bit), C302.

**Comment by acontributor0** [comment]
I have the same problem
My solution is turn on night light then turn it back off.

**Comment by visor841** [comment]
I have the same problem on 70.0.3538 with the Lenovo c630. Flashing night light fixes it until I go back to linux.

**Comment by Lightsockie** [comment]
Another +1 datapoint. Using Google Pixel 2018, `Version 71.0.3578.85 (Official Build) beta (64-bit)`

Workaround with Night light Mode works for me too
```
name: cancer
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/cancer...
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: audio,chrome-dev,core,cli-extra,extension,xorg,xiwi,lxde,touch
host: version 11151.51.0 (Official Build) beta-channel eve 
kernel: Linux localhost 4.4.159-15346-gc5e629939ae0 #1 SMP PREEMPT Mon Dec 3 22:41:11 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/cancer...
```

**Comment by lbaerveldt** [comment]
I'm having the same issue. Using Google Pixelbook, 71.0.3578.98 (Official Build) (64-bit)

Unlike what some others have reported here, the workaround for me is simply close the lid, re-open and Chrome OS is back to normal.

Chroot is standard xfce xenial.

**Comment by devdeepray** [comment]
Zooming in and out by using Ctrl + Shift + '+' followed by Ctrl + Shift + '-' also fixes it after switching back to CrOS.

**Comment by pshotton** [comment]
Nice! Thank you very much.

**Comment by lbaerveldt** [comment]
So it looks like basically anything that forces a screen refresh resolves the problem (at least until the time you swtich to chroot and then back).

**Comment by irwineffect** [comment]
I'm running 71.0.3578.127 (Official Build) (64-bit) on an ASUS c302 (cave). I used to very rarely see this issue, but now the colors get corrupted the first time after switching back to chromeos from crouton. None of the suggested screen refresh techniques return the colors to normal, the only thing I've found that works for me is a reboot. Chroot is xenial with i3wm.

**Comment by Clearia** [comment]
The bug in asus c223n is not repair.

**Comment by estevez-dev** [comment]
DELL Inspiron Chromebook 14
The same issue.
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190120145639~master:5bf96711
release: xenial
architecture: amd64
xmethod: xorg
targets: unity,unity-desktop,gtk-extra,x11,audio,core,keyboard,extension
host: version 11316.165.0 (Official Build) stable-channel nami 
kernel: Linux localhost 4.4.164-15546-gd8c7defc947f #1 SMP PREEMPT Sun Mar 3 22:58:16 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
Quick fix: `Ctrl`+`Alt`+`Refresh` to enter dev console, then `Ctrl`+`Alt`+`Back`.

**Comment by Clearia** [comment]
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190120145639~master:5bf96711
release: bionic
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,extension,keyboard,audio,xfce
host: version 11895.21.0 (Official Build) dev-channel coral 
kernel: Linux localhost 4.4.176-16032-ga91d6ee3c7f6 #1 SMP PREEMPT Wed Mar 20 00:25:14 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by hackerjsimon** [comment]
i found a fix
CTRL-SHIFT-Refresh a few times till you get your screen normal

**Comment by Kirzem** [comment]
I've still got this problem. None of the workarounds help me. I have to reboot the machine every time.

Using a Samsung Chromebook Pro (Caroline)
Version 74.0.3729.159 (Official Build) (64-bit)

Any new information or tips?

**Comment by Antoine1979** [comment]
Same here nothing works and I have to reboot.

Computer used Acer Chromebook CB713-1W-30S8 

thanks

**Comment by TesseractCat** [comment]
I'm experiencing the same issue on my C302CA running Chrome OS version 75.0.3770.129. None of the solutions, aside from rebooting, seem to work.

Thanks, and I hope a solution is discovered soon.

**Comment by visor841** [comment]
It works! Thank you so much!

**Comment by pshotton** [comment]
Very glad to see this fixed. However when I try and update it fails:

sed: can't read tests/cras_test_client.c: No such file or directory
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.

I've raised https://github.com/dnschneid/crouton/issues/4115 for this.

Thanks
